USE [master]
GO

/****** Object:  Database [GSoftPosNew]    Script Date: 8/13/2025 11:57:02 AM ******/
CREATE DATABASE [GSoftPosNew]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GSoftPosNew', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\GSoftPosNew.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'GSoftPosNew_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\GSoftPosNew_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GSoftPosNew].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [GSoftPosNew] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [GSoftPosNew] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [GSoftPosNew] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [GSoftPosNew] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [GSoftPosNew] SET ARITHABORT OFF 
GO

ALTER DATABASE [GSoftPosNew] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [GSoftPosNew] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [GSoftPosNew] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [GSoftPosNew] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [GSoftPosNew] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [GSoftPosNew] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [GSoftPosNew] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [GSoftPosNew] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [GSoftPosNew] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [GSoftPosNew] SET  DISABLE_BROKER 
GO

ALTER DATABASE [GSoftPosNew] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [GSoftPosNew] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [GSoftPosNew] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [GSoftPosNew] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [GSoftPosNew] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [GSoftPosNew] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [GSoftPosNew] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [GSoftPosNew] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [GSoftPosNew] SET  MULTI_USER 
GO

ALTER DATABASE [GSoftPosNew] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [GSoftPosNew] SET DB_CHAINING OFF 
GO

ALTER DATABASE [GSoftPosNew] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [GSoftPosNew] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [GSoftPosNew] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [GSoftPosNew] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [GSoftPosNew] SET QUERY_STORE = OFF
GO

ALTER DATABASE [GSoftPosNew] SET  READ_WRITE 
GO

